"""Single canonical field registry — THE Single Source of Truth.

Every module (import, mapping, validation, units, UI, export, AI) MUST
reference this registry rather than maintaining independent dictionaries.

FieldSpec contains:
- path: canonical field identifier (e.g., "mud_report.mw")
- quantity: data type for unit conversion (e.g., "density")
- unit: canonical storage unit (e.g., "ppg")
- critical: whether the field is required for valid import
- aliases: list of known header/label variations
- min_value / max_value: engineering validation bounds
- description: human-readable description
"""

from dataclasses import dataclass, field
from typing import List, Optional


@dataclass(frozen=True)
class FieldSpec:
    path: str
    quantity: str = "text"
    unit: str = ""
    critical: bool = False
    aliases: tuple = ()
    min_value: Optional[float] = None
    max_value: Optional[float] = None
    description: str = ""


# fmt: off
_FIELD_DEFS = [
    # ── Well Info ──────────────────────────────────────────────
    FieldSpec("well_info.name", "text", "", True,
              ("well name", "well", "wellname", "well_name", "well no", "well number", "well id", "well designation"),
              description="Well name or designation"),
    FieldSpec("well_info.report_date", "date", "", True,
              ("report date", "date", "rpt date"),
              description="Report date"),
    FieldSpec("well_info.well_type", "text", "", False,
              ("well type", "welltype", "type of well"),
              description="Well type (Development, Exploration, etc.)"),
    FieldSpec("well_info.well_shape", "text", "", False,
              ("well shape", "well profile", "well trajectory type"),
              description="Well shape (Vertical, J-shape, S-shape, etc.)"),
    FieldSpec("well_info.rig_name", "text", "", False,
              ("rig name", "rig", "rig no", "rig number", "rigname"),
              description="Drilling rig name"),
    FieldSpec("well_info.field_name", "text", "", False,
              ("field", "field name", "fieldname", "oil field"),
              description="Oil/gas field name"),
    FieldSpec("well_info.operator", "text", "", False,
              ("operator", "operating company", "op company"),
              description="Operating company"),
    FieldSpec("well_info.client", "text", "", False,
              ("client", "client name", "company", "oil company"),
              description="Client company"),
    FieldSpec("well_info.client_rep", "text", "", False,
              ("client rep", "client representative", "company rep"),
              description="Client representative"),
    FieldSpec("well_info.drilling_contractor", "text", "", False,
              ("drilling contractor", "contractor", "drill contractor"),
              description="Drilling contractor"),
    FieldSpec("well_info.section_name", "text", "", False,
              ("hole section", "section", "hole section (inch)", "hole size"),
              description="Current hole section"),
    FieldSpec("well_info.target_depth", "length", "m", False,
              ("estimated final depth", "target depth", "total depth", "final depth", "td", "efd"),
              min_value=0, max_value=15000,
              description="Estimated final depth"),
    FieldSpec("well_info.water_depth", "length", "m", False,
              ("water depth", "offshore water depth", "sea depth"),
              min_value=0, max_value=5000,
              description="Water depth"),
    FieldSpec("well_info.gle_msl", "length", "m", False,
              ("gle-msl", "gle msl", "ground level elevation"),
              description="Ground Level Elevation above MSL"),
    FieldSpec("well_info.rte_msl", "length", "m", False,
              ("rte-msl", "rte msl", "rotary table elevation", "kb elevation", "kb-msl"),
              description="Rotary Table Elevation above MSL"),
    FieldSpec("well_info.gle_rte", "length", "m", False,
              ("gle-rte", "gle rte", "rt - wh", "rt-wh"),
              description="GLE to RTE distance"),
    FieldSpec("well_info.formation", "text", "", False,
              ("formation", "formation name", "geological formation"),
              description="Current formation"),
    FieldSpec("well_info.spud_date", "date", "", False,
              ("spud", "spud date", "spud_date"),
              description="Spud date"),
    FieldSpec("well_info.location", "text", "", False,
              ("location", "well location"),
              description="Well location"),
    FieldSpec("well_info.latitude", "text", "", False,
              ("latitude", "lat"),
              description="Latitude coordinate"),
    FieldSpec("well_info.longitude", "text", "", False,
              ("longitude", "lon", "long"),
              description="Longitude coordinate"),
    FieldSpec("well_info.northing", "number", "m", False,
              ("northing", "northing (m)"),
              description="Northing coordinate"),
    FieldSpec("well_info.easting", "number", "m", False,
              ("easting", "easting (m)"),
              description="Easting coordinate"),
    FieldSpec("well_info.operation_manager", "text", "", False,
              ("drilling operation manager", "operation manager", "operations manager"),
              description="Drilling Operations Manager"),
    FieldSpec("well_info.superintendent", "text", "", False,
              ("drilling superintendent", "superintendent"),
              description="Drilling Superintendent"),
    FieldSpec("well_info.supervisor_day", "text", "", False,
              ("drilling supervisor (day)", "supervisor day", "supervisor (day)"),
              description="Drilling Supervisor Day Shift"),
    FieldSpec("well_info.supervisor_night", "text", "", False,
              ("drilling supervisor (night)", "supervisor night", "supervisor (night)"),
              description="Drilling Supervisor Night Shift"),
    FieldSpec("well_info.geologist1", "text", "", False,
              ("well site geologist", "geologist", "well site geology"),
              description="Well Site Geologist"),
    FieldSpec("well_info.tool_pusher_day", "text", "", False,
              ("tool pusher day", "tool pusher", "tool pusher day / night"),
              description="Tool Pusher"),
    FieldSpec("well_info.report_no", "integer", "", False,
              ("report no", "report number", "report no."),
              description="Report number"),

    # ── Daily Report ──────────────────────────────────────────
    FieldSpec("daily_report.report_date", "date", "", True,
              ("report date", "date"),
              description="Daily report date"),
    FieldSpec("daily_report.report_number", "integer", "", False,
              ("report no", "report number"),
              description="Report sequence number"),
    FieldSpec("daily_report.rig_day", "integer", "", False,
              ("rig day", "rig day no"),
              description="Rig day number"),
    FieldSpec("daily_report.depth_0000", "length", "m", False,
              ("md (m)@ 0:00", "md @ 0:00", "depth 0:00", "depth @ 00:00", "md (m) @ 00:00"),
              min_value=0,
              description="Measured depth at midnight"),
    FieldSpec("daily_report.depth_0600", "length", "m", False,
              ("md (m)@ 6:00 am", "md @ 6:00", "depth 6:00", "md (m) @ 06:00"),
              min_value=0,
              description="Measured depth at 06:00"),
    FieldSpec("daily_report.depth_2400", "length", "m", True,
              ("md (m)@ 24:00", "md @ 24:00", "depth 24:00", "md (m) @ 24:00"),
              min_value=0,
              description="Measured depth at 24:00"),
    FieldSpec("daily_report.summary", "text", "", False,
              ("summary", "summary of activities", "daily summary"),
              description="Summary of activities"),
    FieldSpec("daily_report.forecast", "text", "", False,
              ("forecast", "operation forecast", "next 24 hours"),
              description="Operation forecast for next 24 hours"),
    FieldSpec("daily_report.drilled_24hrs", "length", "m", False,
              ("24 hrs drilled", "24 hrs drilled (m)", "drilled 24h"),
              min_value=0,
              description="Meters drilled in last 24 hours"),
    FieldSpec("daily_report.avg_rop_remark", "rate", "m/hr", False,
              ("avg. rop", "avg rop", "average rop"),
              min_value=0,
              description="Average ROP from remark section"),
    FieldSpec("daily_report.lta_day", "integer", "day", False,
              ("lta (day)", "lta days", "lta"),
              description="Lost Time Accident days"),
    FieldSpec("daily_report.actual_rig_days", "number", "day", False,
              ("actual rig days", "rig days"),
              description="Actual rig days"),

    # ── Mud Report ────────────────────────────────────────────
    FieldSpec("mud_report.mw", "density", "ppg", True,
              ("mud weight", "mw", "mud wt", "density", "mud weight (ppg)", "mud weight (pcf)", "max weight"),
              min_value=0, max_value=25,
              description="Mud weight"),
    FieldSpec("mud_report.mud_type", "text", "", False,
              ("mud type", "fluid type", "mud system"),
              description="Mud type (Ben. Mud, KCl, etc.)"),
    FieldSpec("mud_report.pv", "viscosity", "cp", False,
              ("pv", "plastic viscosity", "pv (cp)"),
              min_value=0,
              description="Plastic Viscosity"),
    FieldSpec("mud_report.yp", "stress", "lb/100ft2", False,
              ("yp", "yield point", "yp (lb/100ft2)"),
              description="Yield Point"),
    FieldSpec("mud_report.funnel_vis", "viscosity", "sec", False,
              ("funnel vis", "funnel viscosity", "funnel vis (sec/qt)"),
              min_value=0,
              description="Marsh Funnel Viscosity"),
    FieldSpec("mud_report.gel_10s", "stress", "lb/100ft2", False,
              ("gel 10s", "gel 10 s", "gel 10s (lb/100ft2)"),
              min_value=0,
              description="Gel strength at 10 seconds"),
    FieldSpec("mud_report.gel_10m", "stress", "lb/100ft2", False,
              ("gel 10min", "gel 10 min", "gel 10min (lb/100ft2)"),
              min_value=0,
              description="Gel strength at 10 minutes"),
    FieldSpec("mud_report.fl", "volume", "ml", False,
              ("api fluid loss", "fluid loss", "filtrate", "api fluid loss (cc/30 min)"),
              min_value=0,
              description="API Fluid Loss"),
    FieldSpec("mud_report.cake_thickness", "length", "mm", False,
              ("filter cake", "cake thickness", "filter cake (1/32\")"),
              min_value=0,
              description="Filter cake thickness"),
    FieldSpec("mud_report.ph", "number", "", False,
              ("ph", "ph value"),
              min_value=0, max_value=14,
              description="pH"),
    FieldSpec("mud_report.temperature", "temperature", "C", False,
              ("temperature", "mud temp", "flowline temp"),
              description="Mud temperature"),
    FieldSpec("mud_report.solid_percent", "number", "%", False,
              ("solid %", "solids", "solid (% vol)", "solid percent"),
              min_value=0, max_value=100,
              description="Solid content percentage"),
    FieldSpec("mud_report.oil_percent", "number", "%", False,
              ("oil %", "oil / water", "oil / water (% vol)"),
              min_value=0, max_value=100,
              description="Oil percentage"),
    FieldSpec("mud_report.water_percent", "number", "%", False,
              ("water %", "water percent"),
              min_value=0, max_value=100,
              description="Water percentage"),
    FieldSpec("mud_report.chloride", "number", "mg/L", False,
              ("chloride", "chloride (mg/lit)"),
              min_value=0,
              description="Chloride concentration"),
    FieldSpec("mud_report.total_hardness", "number", "mg/L", False,
              ("total hardness", "hardness (mg/lit)"),
              min_value=0,
              description="Total hardness"),
    FieldSpec("mud_report.pf_mf", "text", "", False,
              ("pf / mf", "pf/mf", "phenolphthalein alkalinity"),
              description="Pf / Mf alkalinity"),
    FieldSpec("mud_report.calcium", "number", "mg/L", False,
              ("ca++", "calcium", "ca++ (mg/lit)"),
              min_value=0,
              description="Calcium concentration"),
    FieldSpec("mud_report.mbt", "number", "lb/bbl", False,
              ("mbt", "methylene blue test", "mbt (lb/bbl)"),
              min_value=0,
              description="Methylene Blue Test"),
    FieldSpec("mud_report.kcl", "number", "%", False,
              ("kcl", "kcl (% wt)", "kcl concentration"),
              min_value=0, max_value=100,
              description="KCl concentration"),

    # ── Drilling Parameters ───────────────────────────────────
    FieldSpec("drilling_params.bit_no", "text", "", False,
              ("bit no", "bit no.", "bit number"),
              description="Bit number"),
    FieldSpec("drilling_params.bit_size", "length", "in", True,
              ("bit size", "bit size (inch)", "bit diameter"),
              min_value=0, max_value=36,
              description="Bit size"),
    FieldSpec("drilling_params.bit_type", "text", "", False,
              ("bit type", "bit design"),
              description="Bit type"),
    FieldSpec("drilling_params.iadc_code", "text", "", False,
              ("iadc code", "iadc", "iadc dull"),
              description="IADC dull grading code"),
    FieldSpec("drilling_params.manufacturer", "text", "", False,
              ("bit manufacture", "manufacturer", "bit manufacturer"),
              description="Bit manufacturer"),
    FieldSpec("drilling_params.depth_in", "length", "m", False,
              ("depth in", "depth in (m)", "in depth"),
              min_value=0,
              description="Bit run start depth"),
    FieldSpec("drilling_params.depth_out", "length", "m", False,
              ("depth out", "depth out (m)", "out depth"),
              min_value=0,
              description="Bit run end depth"),
    FieldSpec("drilling_params.hours_on_bottom", "number", "hr", False,
              ("bit hours on bottom", "hours on bottom"),
              min_value=0,
              description="Hours on bottom"),
    FieldSpec("drilling_params.avg_rop", "rate", "m/hr", False,
              ("average rop", "avg rop", "rop"),
              min_value=0,
              description="Average ROP"),
    FieldSpec("drilling_params.bit_drilled", "length", "m", False,
              ("bit drilled", "bit drilled (m)", "meterage"),
              min_value=0,
              description="Meters drilled on this bit"),
    FieldSpec("drilling_params.bit_cum_drilled", "length", "m", False,
              ("bit cum. drilled", "cumulative drilled"),
              min_value=0,
              description="Cumulative meters drilled"),
    FieldSpec("drilling_params.bit_cum_hrs_on_bottom", "number", "hr", False,
              ("bit cum. hrs on bottom", "cumulative hours"),
              min_value=0,
              description="Cumulative hours on bottom"),
    FieldSpec("drilling_params.cum_bit_avg_rop", "rate", "m/hr", False,
              ("cum.bit ave rop", "cumulative average rop"),
              min_value=0,
              description="Cumulative bit average ROP"),
    FieldSpec("drilling_params.bit_revolution", "number", "k.rev", False,
              ("bit revolution", "bit rotation", "bit revolution (k.rev)"),
              min_value=0,
              description="Bit revolutions in thousands"),
    FieldSpec("drilling_params.tfa", "area", "in2", False,
              ("tfa", "tfa (in^2)", "tfa ( sq in)", "total flow area"),
              min_value=0,
              description="Total Flow Area"),
    FieldSpec("drilling_params.wob_min", "force", "klbf", False,
              ("wob min", "min wob", "w.o.b min"),
              min_value=0,
              description="Weight on Bit minimum"),
    FieldSpec("drilling_params.wob_max", "force", "klbf", False,
              ("wob max", "max wob", "w.o.b", "w.o.b (klbs)", "weight on bit"),
              min_value=0,
              description="Weight on Bit maximum"),
    FieldSpec("drilling_params.rpm_min", "rpm", "rpm", False,
              ("rpm min", "min rpm", "surf. rpm min"),
              min_value=0,
              description="RPM minimum"),
    FieldSpec("drilling_params.rpm_max", "rpm", "rpm", False,
              ("rpm max", "max rpm", "surf. rpm", "surf. rpm ( rev/gal)"),
              min_value=0,
              description="RPM maximum"),
    FieldSpec("drilling_params.torque_min", "torque", "ft_lbf", False,
              ("torque min", "min torque"),
              min_value=0,
              description="Torque minimum"),
    FieldSpec("drilling_params.torque_max", "torque", "ft_lbf", False,
              ("torque max", "max torque", "torque", "torque (kft-lbs)"),
              min_value=0,
              description="Torque maximum"),
    FieldSpec("drilling_params.pump_pressure_min", "pressure", "psi", False,
              ("spp min", "min spp", "min pressure"),
              min_value=0,
              description="Standpipe pressure minimum"),
    FieldSpec("drilling_params.pump_pressure_max", "pressure", "psi", False,
              ("spp max", "max spp", "pump pressure", "pump pressure (psi)"),
              min_value=0,
              description="Standpipe pressure maximum"),
    FieldSpec("drilling_params.pump_output_min", "flow_rate", "gpm", False,
              ("pump output min", "spm min", "min spm"),
              min_value=0,
              description="Pump output minimum"),
    FieldSpec("drilling_params.pump_output_max", "flow_rate", "gpm", False,
              ("pump output max", "spm max", "max spm"),
              min_value=0,
              description="Pump output maximum"),
    FieldSpec("drilling_params.pump_liner_size", "text", "", False,
              ("pump liner size", "pump liner size (inch)"),
              description="Pump liner size"),

    # ── Time Log ──────────────────────────────────────────────
    FieldSpec("time_log.time_from", "time", "", False,
              ("from", "time from", "start time"),
              description="Activity start time"),
    FieldSpec("time_log.time_to", "time", "", False,
              ("to", "time to", "end time"),
              description="Activity end time"),
    FieldSpec("time_log.duration", "number", "hr", False,
              ("hrs", "duration", "hours"),
              min_value=0, max_value=24,
              description="Activity duration in hours"),
    FieldSpec("time_log.main_phase", "text", "", False,
              ("main phase", "phase"),
              description="Main activity phase"),
    FieldSpec("time_log.main_code", "code", "", True,
              ("code", "main code", "phase code"),
              description="Main activity code"),
    FieldSpec("time_log.sub_code", "code", "", True,
              ("sub code", "sub-code", "activity code"),
              description="Sub activity code"),
    FieldSpec("time_log.status", "text", "", False,
              ("status",),
              description="Activity status (PLN, NPT, etc.)"),
    FieldSpec("time_log.activity_description", "text", "", False,
              ("rig activity", "activity", "description", "activity description", "remark"),
              description="Activity description"),
    FieldSpec("time_log.contractor", "text", "", False,
              ("contractor", "service provider"),
              description="Contractor performing activity"),

    # ── Survey / Trajectory ───────────────────────────────────
    FieldSpec("survey.md", "length", "m", True,
              ("md", "md (m)", "measured depth", "m.d"),
              min_value=0,
              description="Measured Depth"),
    FieldSpec("survey.inc", "angle", "deg", False,
              ("inc", "incl.", "inclination"),
              min_value=0, max_value=180,
              description="Inclination"),
    FieldSpec("survey.azi", "angle", "deg", False,
              ("azi", "azimuth"),
              min_value=0, max_value=360,
              description="Azimuth"),
    FieldSpec("survey.tvd", "length", "m", False,
              ("tvd", "tvd (m)", "true vertical depth"),
              min_value=0,
              description="True Vertical Depth"),
    FieldSpec("survey.north", "length", "m", False,
              ("north", "north (m)", "northing"),
              description="Northing displacement"),
    FieldSpec("survey.east", "length", "m", False,
              ("east", "east (m)", "easting"),
              description="Easting displacement"),
    FieldSpec("survey.dls", "dls", "deg/30m", False,
              ("dls", "dogleg severity", "dogleg"),
              min_value=0,
              description="Dogleg Severity"),
    FieldSpec("survey.tool", "text", "", False,
              ("tool",),
              description="Survey tool (MWD, Gyro, etc.)"),

    # ── Bulk Materials ────────────────────────────────────────
    FieldSpec("bulk_material.material_name", "text", "", False,
              ("product type", "material", "chemical", "material name"),
              description="Material/chemical name"),
    FieldSpec("bulk_material.unit", "text", "", False,
              ("unit", "uom"),
              description="Unit of measure"),
    FieldSpec("bulk_material.received", "volume", "", False,
              ("received", "received qty"),
              min_value=0,
              description="Quantity received"),
    FieldSpec("bulk_material.used", "volume", "", False,
              ("used", "consumed"),
              min_value=0,
              description="Quantity used"),
    FieldSpec("bulk_material.current_stock", "volume", "", False,
              ("on hand", "current stock", "closing stock", "balance"),
              min_value=0,
              description="Current stock on hand"),

    # ── BHA ───────────────────────────────────────────────────
    FieldSpec("bha.component_name", "text", "", False,
              ("item", "component", "component name", "bha item"),
              description="BHA component name"),
    FieldSpec("bha.od", "length", "in", False,
              ("od", "od (in)", "od (inch)", "outer diameter"),
              min_value=0,
              description="Component outer diameter"),
    FieldSpec("bha.length", "length", "m", False,
              ("length", "length (m)"),
              min_value=0,
              description="Component length"),

    # ── Downhole Equipment ────────────────────────────────────
    FieldSpec("downhole.equipment_name", "text", "", False,
              ("equipment", "equipment name", "downhole equipment"),
              description="Downhole equipment name"),
    FieldSpec("downhole.od", "text", "", False,
              ("od (inch)", "od"),
              description="Equipment OD"),
    FieldSpec("downhole.serial_number", "text", "", False,
              ("serial number", "serial no", "s/n"),
              description="Serial number"),
    FieldSpec("downhole.rot_hrs", "number", "hr", False,
              ("rot. hrs", "rotational hours"),
              min_value=0,
              description="Rotational hours"),
    FieldSpec("downhole.cum_hrs", "number", "hr", False,
              ("cum. hrs", "cumulative hours"),
              min_value=0,
              description="Cumulative hours"),

    # ── Formation ─────────────────────────────────────────────
    FieldSpec("formation.name", "text", "", False,
              ("name", "formation", "formation name"),
              description="Formation name"),
    FieldSpec("formation.md_top", "length", "m", False,
              ("m md", "md top", "formation top"),
              min_value=0,
              description="Formation top MD"),
    FieldSpec("formation.tvd", "length", "m", False,
              ("m tvd", "tvd top"),
              min_value=0,
              description="Formation top TVD"),
    FieldSpec("formation.lithology", "text", "", False,
              ("lithology",),
              description="Lithology description"),

    # ── Casing ────────────────────────────────────────────────
    FieldSpec("casing.size", "length", "in", False,
              ("size", "size (in)", "casing size"),
              min_value=0,
              description="Casing size"),
    FieldSpec("casing.depth_from", "length", "m", False,
              ("from", "from (m)", "depth from"),
              min_value=0,
              description="Casing from depth"),
    FieldSpec("casing.depth_to", "length", "m", False,
              ("to", "to (m)", "depth to"),
              min_value=0,
              description="Casing to depth"),
    FieldSpec("casing.grade", "text", "", False,
              ("grade",),
              description="Casing grade"),
    FieldSpec("casing.weight", "number", "ppf", False,
              ("weight", "weight (#)", "weight (ppf)"),
              min_value=0,
              description="Casing weight per foot"),
    FieldSpec("casing.thread", "text", "", False,
              ("thread",),
              description="Casing thread type"),
    FieldSpec("casing.shoe_tvd", "length", "m", False,
              ("shoe (tvd)m", "shoe tvd"),
              min_value=0,
              description="Shoe TVD"),
    FieldSpec("casing.burst_pressure", "pressure", "psi", False,
              ("burst (psi)", "burst pressure"),
              min_value=0,
              description="Burst pressure rating"),
    FieldSpec("casing.collapse_pressure", "pressure", "psi", False,
              ("collapse (psi)", "collapse pressure"),
              min_value=0,
              description="Collapse pressure rating"),

    # ── BOP ───────────────────────────────────────────────────
    FieldSpec("bop.name", "text", "", False,
              ("name", "bop name", "component"),
              description="BOP component name"),
    FieldSpec("bop.type", "text", "", False,
              ("type", "bop type"),
              description="BOP type (RS, U-Type, etc.)"),
    FieldSpec("bop.working_pressure", "pressure", "psi", True,
              ("wp", "w.p (psi)", "working pressure"),
              min_value=0,
              description="Working pressure"),
    FieldSpec("bop.size", "text", "", False,
              ("size", "bop size"),
              description="BOP size"),
    FieldSpec("bop.rams", "text", "", False,
              ("rams",),
              description="Ram type"),
    FieldSpec("bop.last_test", "text", "", False,
              ("last test", "last test date"),
              description="Last pressure test date"),

    # ── Safety ────────────────────────────────────────────────
    FieldSpec("safety.days_without_lti", "integer", "day", False,
              ("days without lta", "days without lti", "lti free days"),
              min_value=0,
              description="Days without Lost Time Incident"),
    FieldSpec("safety.last_bop_test", "text", "", False,
              ("last bop test",),
              description="Last BOP test date"),
    FieldSpec("safety.last_fire_drill", "text", "", False,
              ("last fire drill",),
              description="Last fire drill date"),
    FieldSpec("safety.last_h2s_drill", "text", "", False,
              ("last h2s drill",),
              description="Last H2S drill date"),
    FieldSpec("safety.last_bop_drill", "text", "", False,
              ("last bop drill",),
              description="Last BOP drill date"),
    FieldSpec("safety.wind_speed", "number", "km/h", False,
              ("wind speed", "wind speed (km/h)"),
              min_value=0,
              description="Wind speed"),
    FieldSpec("safety.wind_direction", "text", "", False,
              ("wind direction",),
              description="Wind direction"),
    FieldSpec("safety.temperature", "temperature", "C", False,
              ("temp", "temp(°c)", "temperature"),
              description="Ambient temperature"),
    FieldSpec("safety.visibility", "number", "km", False,
              ("visibility", "visibility (km)"),
              min_value=0,
              description="Visibility"),

    # ── POB ───────────────────────────────────────────────────
    FieldSpec("logistics.pob_rig", "integer", "", False,
              ("oeoc rig", "dfdc rig", "rig crew"),
              min_value=0,
              description="Rig crew POB"),
    FieldSpec("logistics.pob_client", "integer", "", False,
              ("client", "client (kpe)", "client (oiec)"),
              min_value=0,
              description="Client POB"),
    FieldSpec("logistics.pob_msa", "integer", "", False,
              ("msa", "mdr"),
              min_value=0,
              description="MSA/MDR POB"),
    FieldSpec("logistics.pob_service", "integer", "", False,
              ("service company",),
              min_value=0,
              description="Service company POB"),
    FieldSpec("logistics.pob_catering", "integer", "", False,
              ("catering + guard",),
              min_value=0,
              description="Catering + Guard POB"),
    FieldSpec("logistics.pob_labour", "integer", "", False,
              ("labour",),
              min_value=0,
              description="Labour POB"),
    FieldSpec("logistics.pob_other", "integer", "", False,
              ("other",),
              min_value=0,
              description="Other POB"),
    FieldSpec("logistics.pob_total", "integer", "", False,
              ("total pob",),
              min_value=0,
              description="Total POB"),

    # ── Services ──────────────────────────────────────────────
    FieldSpec("service.hole_section", "text", "", False,
              ("hole section",),
              description="Hole section for service"),
    FieldSpec("service.company_name", "text", "", False,
              ("company", "company name", "contractor"),
              description="Service company name"),
    FieldSpec("service.service_type", "text", "", False,
              ("service", "service type"),
              description="Service type"),
    FieldSpec("service.date_in", "text", "", False,
              ("date in",),
              description="Date in"),
    FieldSpec("service.date_out", "text", "", False,
              ("date out",),
              description="Date out"),
    FieldSpec("service.duration", "number", "day", False,
              ("duration (day)", "duration"),
              min_value=0,
              description="Service duration in days"),
    FieldSpec("service.job_description", "text", "", False,
              ("job description",),
              description="Job description"),

    # ── Cost ──────────────────────────────────────────────────
    FieldSpec("cost.description", "text", "", False,
              ("cost description", "expense", "item"),
              description="Cost description"),
    FieldSpec("cost.amount", "currency", "", False,
              ("amount", "cost", "total cost"),
              description="Cost amount"),
    FieldSpec("cost.category", "text", "", False,
              ("category", "cost category"),
              description="Cost category"),
    FieldSpec("cost.planned_cost", "currency", "", False,
              ("planned cost", "budget", "afe"),
              description="Planned cost"),
    FieldSpec("cost.actual_cost", "currency", "", False,
              ("actual cost",),
              description="Actual cost"),

    # ── NPT ───────────────────────────────────────────────────
    FieldSpec("npt.npt_category", "text", "", False,
              ("npt category", "npt type"),
              description="NPT category"),
    FieldSpec("npt.npt_code", "text", "", False,
              ("npt code",),
              description="NPT code"),
    FieldSpec("npt.duration_hours", "number", "hr", False,
              ("npt hours", "npt duration"),
              min_value=0,
              description="NPT duration"),
    FieldSpec("npt.responsible_party", "text", "", False,
              ("responsible", "npt responsible", "responsible party"),
              description="NPT responsible party"),

    # ── Cement Additives ──────────────────────────────────────
    FieldSpec("cement.material_type", "text", "", False,
              ("material type", "cement type"),
              description="Cement additive type"),
    FieldSpec("cement.slurry_density", "density", "ppg", False,
              ("slurry density", "slurry weight"),
              min_value=0,
              description="Cement slurry density"),
    FieldSpec("cement.used", "volume", "", False,
              ("used", "cement volume", "cement used"),
              min_value=0,
              description="Cement used"),
    FieldSpec("cement.received", "volume", "", False,
              ("received",),
              min_value=0,
              description="Cement received"),
    FieldSpec("cement.on_hand", "volume", "", False,
              ("on hand",),
              min_value=0,
              description="Cement on hand"),
    FieldSpec("cement.unit", "text", "", False,
              ("unit",),
              description="Cement unit"),

    # ── Solid Control ─────────────────────────────────────────
    FieldSpec("solid_control.equipment", "text", "", False,
              ("equipment",),
              description="Solid control equipment"),
    FieldSpec("solid_control.size_cones", "text", "", False,
              ("size/# cones",),
              description="Screen size / cones"),
    FieldSpec("solid_control.daily_hrs", "number", "hr", False,
              ("daily hrs",),
              min_value=0,
              description="Daily hours"),
    FieldSpec("solid_control.cum_hrs", "number", "hr", False,
              ("cum hrs",),
              min_value=0,
              description="Cumulative hours"),

    # ── Transport ─────────────────────────────────────────────
    FieldSpec("transport.name", "text", "", False,
              ("name", "vessel name"),
              description="Vessel/vehicle name"),
    FieldSpec("transport.arrival_time", "text", "", False,
              ("arrival time",),
              description="Arrival time"),
    FieldSpec("transport.arrival_date", "text", "", False,
              ("arrival date",),
              description="Arrival date"),
    FieldSpec("transport.pax_in", "integer", "", False,
              ("pax in", "no. of pax in"),
              min_value=0,
              description="Passengers in"),
    FieldSpec("transport.departure_time", "text", "", False,
              ("departure time",),
              description="Departure time"),
    FieldSpec("transport.departure_date", "text", "", False,
              ("departure date",),
              description="Departure date"),
    FieldSpec("transport.status", "text", "", False,
              ("status",),
              description="Transport status"),

    # ── Lookahead ─────────────────────────────────────────────
    FieldSpec("lookahead.date", "text", "", False,
              ("date",),
              description="Lookahead date"),
    FieldSpec("lookahead.activity", "text", "", False,
              ("activity",),
              description="Planned activity"),

    # ── SCR Data ──────────────────────────────────────────────
    FieldSpec("scr.pump", "text", "", False,
              ("pump",),
              description="Pump identifier"),
    FieldSpec("scr.spm", "number", "spm", False,
              ("spm",),
              min_value=0,
              description="Strokes per minute"),
    FieldSpec("scr.fr_gpm", "number", "gpm", False,
              ("fr (gpm)", "fr gpm"),
              min_value=0,
              description="Flow rate in GPM"),
    FieldSpec("scr.spp", "number", "psi", False,
              ("spp",),
              min_value=0,
              description="Standpipe pressure"),
]
# fmt: on


# Build the registry
FIELD_SPECS = {spec.path: spec for spec in _FIELD_DEFS}
CANONICAL_FIELDS = frozenset(FIELD_SPECS)

# Build alias → canonical field lookup (centralized, single source)
_ALIAS_LOOKUP = {}
for spec in _FIELD_DEFS:
    for alias in spec.aliases:
        normalized = alias.lower().strip()
        if normalized not in _ALIAS_LOOKUP:
            _ALIAS_LOOKUP[normalized] = spec.path

# Quantity → canonical unit lookup
_QUANTITY_UNITS = {}
for spec in _FIELD_DEFS:
    if spec.quantity and spec.unit and spec.quantity not in _QUANTITY_UNITS:
        _QUANTITY_UNITS[spec.quantity] = spec.unit


def get_critical_fields() -> frozenset:
    """Return the set of field paths that are marked critical."""
    return frozenset(path for path, spec in FIELD_SPECS.items() if spec.critical)


def get_fields_by_quantity(quantity: str) -> list:
    """Return field paths matching a given quantity type."""
    return [path for path, spec in FIELD_SPECS.items() if spec.quantity == quantity]


def get_field_spec(path: str) -> FieldSpec:
    """Get the FieldSpec for a canonical field path, or None if not found."""
    return FIELD_SPECS.get(path)


def lookup_alias(alias_text: str) -> str:
    """Look up a header/label alias and return the canonical field path.
    
    This is THE centralized alias lookup — all modules must use this
    instead of maintaining independent alias dictionaries.
    """
    normalized = alias_text.lower().strip()
    # Remove common suffixes
    cleaned = normalized.rstrip(':').strip()
    cleaned = cleaned.replace('(', '').replace(')', '').strip()
    
    # Try exact match
    result = _ALIAS_LOOKUP.get(cleaned)
    if result:
        return result
    
    # Try with common separators normalized
    for sep in ['_', '-', '/']:
        alt = cleaned.replace(sep, ' ')
        result = _ALIAS_LOOKUP.get(alt)
        if result:
            return result
    
    return ""


def get_quantity_unit(quantity: str) -> str:
    """Get the canonical unit for a quantity."""
    return _QUANTITY_UNITS.get(quantity, "")


def get_engineering_bounds(path: str):
    """Get engineering validation bounds for a field.
    
    Returns (min_value, max_value) or (None, None) if no bounds defined.
    """
    spec = FIELD_SPECS.get(path)
    if spec:
        return spec.min_value, spec.max_value
    return None, None
